CREATE SCHEMA IF NOT EXISTS WIS;

CREATE TABLE WIS.INT_E_CONFIRMA_FATURAMENTO (
	"CD_EMPRESA" NUMBER(4,0),
	"CD_DEPOSITO" VARCHAR2(4),
	"NU_PEDIDO" VARCHAR2(30),
	"CD_CLIENTE" VARCHAR2(20) NOT NULL ,
	"CD_CARGA" NUMBER(15,0),
	"NU_NOTA_FISCAL" VARCHAR2(12),
	"NU_SERIE_NOTA" VARCHAR2(3),
	"DT_ARROW" DATE,
	"DT_EMISSAO_NF" DATE,
	"ID_PROCESSADO" VARCHAR2(1),
	"DT_PROCESSADO" DATE,
	"DT_TIMESTAMP" TIMESTAMP,
	"DS_ERRO" VARCHAR2(500),
	"CODDOCA" NUMBER(5,0),
	"NU_VOLUME_TRANSPORTE" NUMBER(8,0),
	"CD_TRANSPORTADORA" VARCHAR2(10) NOT NULL ,
	"DS_TRANSPORTADORA" VARCHAR2(100) not null ,
	"CD_SELLER" NUMBER(22,0) not null ,
	"CD_CNPJ_SELLER" NUMBER(15,0) not null ,
	"NUM_ETIQUETA_FULL" VARCHAR2(30)
) ;



